### ISSUE TITLE
No virtual method intValueExact()I in class Ljava/math/BigInteger

### ISSUE THREAD

**Issue by Nardeep** [filip26/iridium-cbor-ld#6]
While using this  CborLd.decoder(cborArrayBuffer).decode() , I got below exception .Please help me to resolve this.

j java.lang.NoSuchMethodError: No virtual method intValueExact()I in class Ljava/math/BigInteger; or its super classes (declaration of 'java.math.BigInteger' appears in /system/framework/core-libart.jar)
        at com.apicatalog.cborld.dictionary.ContextDictionary.getValue(ContextDictionary.java:61)
        at com.apicatalog.cborld.decoder.value.ContextValueDecoder.decode(ContextValueDecoder.java:30)
        at com.apicatalog.cborld.db.DbDecoderMapping.decodeValue(DbDecoderMapping.java:47)
        at com.apicatalog.cborld.db.-$$Lambda$1s72bMfOEkNzfdJVTiqh5r3j3MQ.decode(Unknown Source:2)
        at com.apicatalog.cursor.cbor.CborCursor.entry(CborCursor.java:118)
        at com.apicatalog.cursor.cbor.CborMapCursor.entry(CborMapCursor.java:81)
        at com.apicatalog.cborld.context.ObjectExpansion.initLocalContext(ObjectExpansion.java:173)
        at com.apicatalog.cborld.context.ObjectExpansion.expand(ObjectExpansion.java:96)
        at com.apicatalog.cborld.context.Expansion.compute(Expansion.java:120)
        at com.apicatalog.cborld.context.Expansion.typeMapping(Expansion.java:124)
        at com.apicatalog.cborld.context.Context.from(Context.java:68)
        at com.apicatalog.cborld.db.DbMappingProvider.getDecoderMapping(DbMappingProvider.java:50)
        at com.apicatalog.cborld.decoder.Decoder.decodeCompressed(Decoder.java:227)
        at com.apicatalog.cborld.decoder.Decoder.decodeCompressed(Decoder.java:218)
        at com.apicatalog.cborld.decoder.Decoder.decode(Decoder.java:189)

**Comment by filip26** [comment]
Hi,
thank you for reporting the issue, it's related to Android only as Android OS re-implements `java.*` libraries. [`BigInteger.*Exact()`](https://developer.android.com/reference/java/math/BigInteger#intValueExact()) methods are supported by Android API Level 31 and higher. 

Please use branch [android-level-23](https://github.com/filip26/iridium-cbor-ld/tree/feat/android-level-23).
